### ISSUE TITLE
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor

### ISSUE THREAD

**Issue by tianyma** [ezliu/dream#6] opened 2021-06-05 08:07 UTC
I follow the example and execute 
```
python3 main.py dream -b environment=\"miniworld_sign\" -c configs/default.json -c configs/miniworld.json
```
but I failed, it seems to be a device error.
```
Traceback (most recent call last):
  File "/home/tianyun/research/rl-samples/dream/main.py", line 385, in <module>
    main()
  File "/home/tianyun/research/rl-samples/dream/main.py", line 250, in main
    episode, _ = run_episode(
  File "/home/tianyun/research/rl-samples/dream/main.py", line 55, in run_episode
    action, next_hidden_state = policy.act(
  File "/home/tianyun/research/rl-samples/dream/dqn.py", line 91, in act
    return self._dqn.act(state, prev_hidden_state=prev_hidden_state, test=test)
  File "/home/tianyun/research/rl-samples/dream/dqn.py", line 418, in act
    q_values, hidden_state = self._Q([[state]], prev_hidden_state)
  File "/home/tianyun/anaconda3/envs/rl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tianyun/research/rl-samples/dream/dqn.py", line 467, in forward
    state_embedding, hidden_state = self._state_embedder(states, hidden_states)
  File "/home/tianyun/anaconda3/envs/rl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tianyun/research/rl-samples/dream/embed.py", line 303, in forward
    trajectory_embed, _ = self._trajectory_embedder(
  File "/home/tianyun/anaconda3/envs/rl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tianyun/research/rl-samples/dream/embed.py", line 240, in forward
    self._compute_contexts(trajectories))
  File "/home/tianyun/research/rl-samples/dream/embed.py", line 160, in _compute_contexts
    padded_transitions = nn.utils.rnn.pack_padded_sequence(
  File "/home/tianyun/anaconda3/envs/rl/lib/python3.9/site-packages/torch/nn/utils/rnn.py", line 245, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor
```
I try to only use CPU in **main.py**, but still fail, the error message is 
```
Traceback (most recent call last):
  File "/home/tianyun/research/rl-samples/dream/main.py", line 385, in <module>
    main()
  File "/home/tianyun/research/rl-samples/dream/main.py", line 250, in main
    episode, _ = run_episode(
  File "/home/tianyun/research/rl-samples/dream/main.py", line 55, in run_episode
    action, next_hidden_state = policy.act(
  File "/home/tianyun/research/rl-samples/dream/dqn.py", line 91, in act
    return self._dqn.act(state, prev_hidden_state=prev_hidden_state, test=test)
  File "/home/tianyun/research/rl-samples/dream/dqn.py", line 418, in act
    q_values, hidden_state = self._Q([[state]], prev_hidden_state)
  File "/home/tianyun/anaconda3/envs/rl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tianyun/research/rl-samples/dream/dqn.py", line 467, in forward
    state_embedding, hidden_state = self._state_embedder(states, hidden_states)
  File "/home/tianyun/anaconda3/envs/rl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tianyun/research/rl-samples/dream/embed.py", line 303, in forward
    trajectory_embed, _ = self._trajectory_embedder(
  File "/home/tianyun/anaconda3/envs/rl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tianyun/research/rl-samples/dream/embed.py", line 240, in forward
    self._compute_contexts(trajectories))
  File "/home/tianyun/research/rl-samples/dream/embed.py", line 174, in _compute_contexts
    transition_hidden_states = torch.cat(
RuntimeError: All input tensors must be on the same device. Received cuda:0 and cpu
``` 
then I only use CPU in embed.py, and I success to train it. 
Is that a device bug?

**Comment by ezliu** [comment] 2021-06-05 08:20
I am not able to reproduce your issue. Could  you confirm your version of PyTorch by running the following on the command line?

```
python -c "import torch; print(torch.__version__)"
```

It should be 1.4.0

**Comment by tianyma** [comment] 2021-06-05 08:24
> I am not able to reproduce your issue. Could you confirm your version of PyTorch by running the following on the command line?
> 
> ```
> python -c "import torch; print(torch.__version__)"
> ```
> 
> It should be 1.4.0

Thank you for your quick reply! It's my fault, my PyTorch version is 1.8.1.

**Comment by ezliu** [comment] 2021-06-05 08:28
Great! Hopefully that should resolve the issue. I'm marking this as closed, but feel free to re-open if this doesn't resolve the issue.

**Closed by ezliu** 2021-06-05 08:28 UTC
